<header>
    <h2>Order Table</h2>
    <table class="table table-striped table-hover my-4">
        <caption>Order Table</caption>
        <thead>
            <tr>
                <th>User Name</th>
                <th>Zip Code</th>
                <th>Product Name</th>
                <th>Quantity</th>
            </tr>
        </thead>
        <tbody>
            <?php
            echo $display;
            ?>
        </tbody>
    </table>
</header>